In [1]:
import numpy as np

In [2]:
my_array = np.arange(5, 101, 5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [3]:
my_array = my_array[1::2]
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
my_array = my_array.reshape(5, 2)
my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [8]:
my_second_array = my_array - 5
my_second_array

array([[ 5, 15],
       [25, 35],
       [45, 55],
       [65, 75],
       [85, 95]])

In [10]:
res = np.concatenate((my_array, my_second_array), axis=1)
res

array([[ 10,  20,   5,  15],
       [ 30,  40,  25,  35],
       [ 50,  60,  45,  55],
       [ 70,  80,  65,  75],
       [ 90, 100,  85,  95]])

In [12]:
res[1] = res[1] / res[0]
res[2] = res[2] / res[1]
res

array([[ 10,  20,   5,  15],
       [  3,   2,   5,   2],
       [ 16,  30,   9,  27],
       [ 70,  80,  65,  75],
       [ 90, 100,  85,  95]])

In [15]:
unchanged = res[res == res.astype(int)]
unchanged

array([ 10,  20,   5,  15,   3,   2,   5,   2,  16,  30,   9,  27,  70,
        80,  65,  75,  90, 100,  85,  95])

In [16]:
my_array = np.random.random((3, 3))
my_array

array([[0.07093583, 0.08521283, 0.63139928],
       [0.45411996, 0.08041167, 0.237516  ],
       [0.73050231, 0.86708494, 0.97964901]])

In [17]:
my_array[0], my_array[2] = my_array[2], my_array[0]
my_array

array([[0.73050231, 0.86708494, 0.97964901],
       [0.45411996, 0.08041167, 0.237516  ],
       [0.73050231, 0.86708494, 0.97964901]])

In [18]:
print(np.mean(my_array, axis=1))
print()
print(np.median(my_array, axis=1))
print()
print(np.std(my_array, axis=1))

[0.85907875 0.25734921 0.85907875]

[0.86708494 0.237516   0.86708494]

[0.10187114 0.15320898 0.10187114]


In [19]:
max_val = np.max(my_array, axis=1)
ans = my_array / max_val[:, np.newaxis]
ans

array([[0.74567758, 0.88509755, 1.        ],
       [1.        , 0.17707144, 0.52302479],
       [0.74567758, 0.88509755, 1.        ]])